apiVersion: v2
name: aiq-web
description: AI-Q - WEB Profile ()
type: application
version: 2603.15.0-rc11
appVersion: '1.0'
dependencies:
- name: aiq
  version: 0.0.4
  repository: file://../helm-charts-k8s/aiq
  alias: aiq
