apiVersion: v2
name: aiq-web
description: AI-Q - WEB Profile (STG)
type: application
version: 0.0.4
appVersion: '1.0'
dependencies:
- name: aiq
  version: 0.0.4
  repository: file://../../helm-charts-k8s/aiq
  alias: aiq
